#0. movie-collaborate-memory-based
* https://grouplens.org/datasets/movielens/latest/

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
PATH = 'data/ml-latest-small'
movies = pd.read_csv(f'{PATH}/movies.csv')
ratings = pd.read_csv(f'{PATH}/ratings.csv')

movies.shape, ratings.shape

((9742, 3), (100836, 4))

#1. 데이터 전처리

In [ ]:
# 유저별 영화평점 행렬 만들기
# 'userId', 'movieId', 'rating'
ratings_matrix = ratings.pivot_table(values="rating", index="userId", columns="movieId")
ratings_matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# ratings 에 영화 제목과 장르 추가하기
# merge로 ratings와 movie를 movieId로 결합
rating_movies = ratings.merge(movies)
rating_movies.head(2)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy

In [ ]:
# 컬럼명이 영화명으로 보이는지 확인
# ratings = ratings[['userId', 'movieId', 'rating']]
ratings_matrix = rating_movies.pivot_table(values="rating",
                                           index="userId", columns="title")
ratings_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [ ]:
# NaN 데이터 0으로 대체
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

#2.사용자 기반 최근접 이웃 협업 필터링
* 행 인덱스가 uesr, 열이 item 이 되도록 만든 행렬로 유사도를 구함

In [ ]:
# sklearn.metrics.pairwise 의 sklearn.metrics.pairwise 가져오기
from sklearn.metrics.pairwise import cosine_similarity
# ratings_matrix 간 유사도 구하기
# df_user_sim
user_sim = cosine_similarity(ratings_matrix, ratings_matrix)
df_user_sim = pd.DataFrame(user_sim, index=ratings_matrix.index,
                           columns=ratings_matrix.index)
df_user_sim.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

## 예시

In [ ]:
# 특정 userId num번과 비슷한 취향의 영화를 보는 userID는?
user_num = 1
sim_user = df_user_sim[user_num].nlargest(10).index[1]
sim_user

266

In [ ]:
# 특정 userId의 영화평점은?
rating_movies.loc[rating_movies["userId"] == user_num, ["title", "rating", "userId"]]

                                title  rating  userId
0                    Toy Story (1995)     4.0       1
215           Grumpier Old Men (1995)     4.0       1
267                       Heat (1995)     4.0       1
369       Seven (a.k.a. Se7en) (1995)     5.0       1
572        Usual Suspects, The (1995)     5.0       1
...                               ...     ...     ...
16056                    Shaft (2000)     4.0       1
16075                    X-Men (2000)     5.0       1
16208          What About Bob? (1991)     4.0       1
16243  Transformers: The Movie (1986)     4.0       1
16250    M*A*S*H (a.k.a. MASH) (1970)     5.0       1

[232 rows x 3 columns]

In [ ]:
# 유사도가 가장 높은 사용자가 본 영화의 평점 찾기
rating_movies.loc[rating_movies["userId"] == sim_user,
                  ["title", "rating", "userId"]].nlargest(10, "rating")

                                                  title  rating  userId
955                                   Braveheart (1995)     5.0     266
1960                                Pulp Fiction (1994)     5.0     266
4730                                       Fargo (1996)     5.0     266
5142                                   Rock, The (1996)     5.0     266
6159                Monty Python's Life of Brian (1979)     5.0     266
6270                              Reservoir Dogs (1992)     5.0     266
6373                                     Platoon (1986)     5.0     266
6699             Monty Python and the Holy Grail (1975)     5.0     266
6875  Star Wars: Episode V - The Empire Strikes Back...     5.0     266
7223  Raiders of the Lost Ark (Indiana Jones and the...     5.0     266

In [ ]:
# 가장 유사도가 높은 사용자가 본 영화 중에 해당 유저가 안 본 영화를 평점이 높은 순으로 추천한다면?
mid = set(rating_movies.loc[rating_movies["userId"].isin([sim_user]), "movieId"]) \
- set(rating_movies.loc[rating_movies["userId"].isin([user_num]), "movieId"])
# mid

In [ ]:
rating_movies[rating_movies["userId"].isin([sim_user]) & rating_movies["movieId"].isin(mid)].nlargest(10, "rating")

,userId,movieId,rating,timestamp,title,genres
20917,266,1079,5.0,945669791,"Fish Called Wanda, A (1988)",Comedy|Crime
21189,266,1199,5.0,945751855,Brazil (1985),Fantasy|Sci-Fi
21530,266,1266,5.0,944980201,Unforgiven (1992),Drama|Western
21611,266,1288,5.0,945669791,This Is Spinal Tap (1984),Comedy
21839,266,1466,5.0,944981273,Donnie Brasco (1997),Crime|Drama
22837,266,2599,5.0,945667950,Election (1999),Comedy
22921,266,2683,5.0,944940240,Austin Powers: The Spy Who Shagged Me (1999),Action|Adventure|Comedy
23008,266,2712,5.0,944940438,Eyes Wide Shut (1999),Drama|Mystery|Thriller
23468,266,3060,5.0,945669397,"Commitments, The (1991)",Comedy|Drama|Musical
27631,266,16,5.0,944981193,Casino (1995),Crime|Drama

#3 .아이템 기반 최근접 이웃 협업 필터링

* 행 인덱스가 item, 열이 user 가 되도록 만든 행렬로 유사도를 구함

In [ ]:
ratings_matrix.T

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5
¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# 행렬의 유사도 측정을 하기 위해 행렬을 transpose함
item_sim = cosine_similarity(ratings_matrix.T, ratings_matrix.T)
df_item_sim = pd.DataFrame(item_sim, index=ratings_matrix.T.index,
                           columns=ratings_matrix.T.index)

In [ ]:
# 아이템간 유사도 측정
df_item_sim

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.141653,0.000000,...,0.000000,0.342055,0.543305,0.707107,0.0,0.000000,0.139431,0.327327,0.000000,0.0
'Hellboy': The Seeds of Creation (2004),0.000000,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Round Midnight (1986),0.000000,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Salem's Lot (2004),0.000000,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Til There Was You (1997),0.000000,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.211467,0.216295,0.097935,0.132489,...,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.192259,0.000000,0.170341,0.0
xXx (2002),0.139431,0.000000,0.000000,0.000000,0.000000,0.0,0.089634,0.000000,0.276512,0.019862,...,0.069716,0.305535,0.173151,0.246482,0.0,0.192259,1.000000,0.270034,0.100396,0.0
xXx: State of the Union (2005),0.327327,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.156764,0.000000,...,0.000000,0.382543,0.177838,0.231455,0.0,0.000000,0.270034,1.000000,0.000000,0.0
¡Three Amigos! (1986),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.372876,0.180009,0.169385,0.249586,...,0.180009,0.000000,0.000000,0.000000,0.0,0.170341,0.100396,0.000000,1.000000,0.0
À nous la liberté (Freedom for Us) (1931),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.0

In [ ]:
df_item_sim['Star Wars: Episode IV - A New Hope (1977)'].nlargest(10)

title
Star Wars: Episode IV - A New Hope (1977)                                         1.000000
Star Wars: Episode V - The Empire Strikes Back (1980)                             0.832407
Star Wars: Episode VI - Return of the Jedi (1983)                                 0.790639
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    0.708834
Matrix, The (1999)                                                                0.663447
Indiana Jones and the Last Crusade (1989)                                         0.641719
Back to the Future (1985)                                                         0.622806
Star Wars: Episode I - The Phantom Menace (1999)                                  0.604377
Terminator, The (1984)                                                            0.596987
Godfather, The (1972)                                                             0.595317
Name: Star Wars: Episode IV - A New Hope (1977), dtype: float64

In [ ]:
df_item_sim['Matrix, The (1999)'].nlargest(10)

title
Matrix, The (1999)                                                                1.000000
Fight Club (1999)                                                                 0.713937
Star Wars: Episode V - The Empire Strikes Back (1980)                             0.700935
Saving Private Ryan (1998)                                                        0.679615
Star Wars: Episode IV - A New Hope (1977)                                         0.663447
Star Wars: Episode VI - Return of the Jedi (1983)                                 0.660984
Lord of the Rings: The Fellowship of the Ring, The (2001)                         0.654128
Sixth Sense, The (1999)                                                           0.651307
Lord of the Rings: The Return of the King, The (2003)                             0.640203
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    0.631107
Name: Matrix, The (1999), dtype: float64

In [ ]:
df_item_sim['Lord of the Rings: The Return of the King, The (2003)'].nlargest(10)

title
Lord of the Rings: The Return of the King, The (2003)            1.000000
Lord of the Rings: The Two Towers, The (2002)                    0.882279
Lord of the Rings: The Fellowship of the Ring, The (2001)        0.874400
Pirates of the Caribbean: The Curse of the Black Pearl (2003)    0.686688
Incredibles, The (2004)                                          0.646247
Matrix, The (1999)                                               0.640203
Batman Begins (2005)                                             0.625739
Shrek (2001)                                                     0.622145
Fight Club (1999)                                                0.622016
Dark Knight, The (2008)                                          0.620637
Name: Lord of the Rings: The Return of the King, The (2003), dtype: float64

In [ ]:
df_item_sim['Zootopia (2016)'].nlargest(10)

title
Zootopia (2016)                                      1.000000
Inside Out (2015)                                    0.601073
Deadpool (2016)                                      0.581750
Big Hero 6 (2014)                                    0.574437
Star Wars: Episode VII - The Force Awakens (2015)    0.565219
Guardians of the Galaxy (2014)                       0.564004
Mad Max: Fury Road (2015)                            0.536005
Doctor Strange (2016)                                0.534756
Kingsman: The Secret Service (2015)                  0.514448
The Lego Movie (2014)                                0.510291
Name: Zootopia (2016), dtype: float64